from enum import StrEnum


class AgentState(StrEnum):
    IDLE = "IDLE"
    LISTENING = "LISTENING"
    TRANSCRIBING = "TRANSCRIBING"
    THINKING = "THINKING"
    USING_TOOL = "USING_TOOL"
    WAITING_FOR_PERMISSION = "WAITING_FOR_PERMISSION"
    SPEAKING = "SPEAKING"
    ERROR = "ERROR"